# generate OpenApi spec and TS client from rust server
openapi:
  cd server && \
  cargo run --bin print-openapi > openapi.json && \
  cd ../web && pnpm orval --config orval.config.cjs

# check that server/openapi.json matches output of print-openapi binary and web/src/lib/apiclient.ts matches output generated by openapi-zod-client from openapi.json
check-openapi:
  #!/usr/bin/bash
  tmpdir='/tmp/myrti-openapi-out'
  cd web && pnpm orval --config orval.config.cjs -o $tmpdir && cd ..
  diff server/openapi.json <(cd server && cargo run --quiet --bin print-openapi) || echo "MISMATCH"
  diff web/src/api/myrti.ts $tmpdir/myrti.ts || echo "MISMATCH"
  diff web/src/api/myrti.zod.ts $tmpdir/myrti.zod.ts || echo "MISMATCH"
