/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * myrti
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

export const getAllAlbumsResponseItem = zod.object({
  changedAt: zod.string().datetime({}),
  createdAt: zod.string().datetime({}),
  description: zod.string().nullish(),
  id: zod.string(),
  name: zod.string().nullish(),
  numAssets: zod.number(),
});
export const getAllAlbumsResponse = zod.array(getAllAlbumsResponseItem);

export const createAlbumBody = zod.object({
  assets: zod.array(zod.string()),
  description: zod.string().nullish(),
  name: zod.string(),
});

export const createAlbumResponse = zod.object({
  albumId: zod.number(),
});

export const getAlbumDetailsParams = zod.object({
  id: zod.string().describe('Album id'),
});

export const getAlbumDetailsResponse = zod.object({
  description: zod.string().nullish(),
  items: zod.array(
    zod
      .union([
        zod.object({
          asset: zod
            .object({
              assetId: zod.string(),
              repFile: zod.object({
                addedAt: zod.string().datetime({}),
                assetRootId: zod.string(),
                fileId: zod.string(),
                height: zod.number(),
                mimeType: zod.string(),
                mirrorCorrection: zod.enum(['none', 'horizontal', 'vertical']),
                pathInRoot: zod.string(),
                rotationCorrection: zod.number(),
                thumbhash: zod.string().nullish(),
                width: zod.number(),
              }),
              takenDate: zod.string().datetime({}),
            })
            .and(
              zod.union([
                zod
                  .object({
                    representations: zod.array(
                      zod.object({
                        format: zod.string(),
                        height: zod.number(),
                        id: zod.string(),
                        size: zod.number(),
                        width: zod.number(),
                      }),
                    ),
                  })
                  .and(
                    zod.object({
                      assetType: zod.enum(['image']),
                    }),
                  ),
                zod
                  .object({
                    hasDash: zod.boolean(),
                  })
                  .and(
                    zod.object({
                      assetType: zod.enum(['video']),
                    }),
                  ),
              ]),
            )
            .and(zod.object({})),
          itemType: zod.enum(['asset']),
        }),
        zod.object({
          itemType: zod.enum(['text']),
          text: zod.string(),
        }),
      ])
      .and(
        zod.object({
          itemId: zod.string(),
        }),
      ),
  ),
  name: zod.string().nullish(),
});

export const appendAssetsToAlbumParams = zod.object({
  id: zod.string().describe('Album id'),
});

export const appendAssetsToAlbumBody = zod.object({
  assetIds: zod.array(zod.string()),
});

export const appendAssetsToAlbumResponse = zod.object({
  success: zod.boolean(),
});

export const deleteAlbumItemsParams = zod.object({
  id: zod.string().describe('Album id'),
});

export const deleteAlbumItemsBody = zod.object({
  itemIds: zod.array(zod.string()),
});

export const deleteAlbumItemsResponseDefault = null;

export const deleteAlbumItemsResponse = zod.unknown().nullable();

export const getAlbumThumbnailParams = zod.object({
  id: zod.string().describe('AlbumId to get thumbnail for'),
  size: zod.string().describe('Thumbnail size'),
  format: zod.enum(['avif', 'webp']).describe('Image format for thumbnail'),
});

export const setAssetsHiddenBody = zod.object({
  assetIds: zod.array(zod.string()),
  what: zod.enum(['hide', 'unhide']),
});

export const getAssetParams = zod.object({
  id: zod.string().describe('AssetId'),
});

export const getAssetResponse = zod.object({
  assetId: zod.string(),
  repFile: zod.object({
    addedAt: zod.string().datetime({}),
    assetRootId: zod.string(),
    fileId: zod.string(),
    height: zod.number(),
    mimeType: zod.string(),
    mirrorCorrection: zod.enum(['none', 'horizontal', 'vertical']),
    pathInRoot: zod.string(),
    rotationCorrection: zod.number(),
    thumbhash: zod.string().nullish(),
    width: zod.number(),
  }),
  takenDate: zod.string().datetime({}),
});

export const setAssetIsSeriesSelectionParams = zod.object({
  id: zod.string().describe('AssetId'),
});

export const setAssetIsSeriesSelectionBody = zod.object({
  isSeriesSelection: zod.boolean(),
});

export const setAssetIsSeriesSelectionResponseSelectionIndicesItemMin = 0;

export const setAssetIsSeriesSelectionResponse = zod.object({
  assetIds: zod.array(zod.string()).describe('All assets in the series'),
  selectionIndices: zod.array(
    zod.number().min(setAssetIsSeriesSelectionResponseSelectionIndicesItemMin),
  ),
  seriesId: zod.string(),
});

export const disableGhiStreamingBody = zod.object({
  fileIds: zod.array(zod.string()),
});

export const disableGhiStreamingResponseDefault = null;

export const disableGhiStreamingResponse = zod.unknown().nullable();

export const regenerateThumbnailBody = zod.object({
  fileIds: zod
    .array(zod.string())
    .nullish()
    .describe('List of FileId, or null to regenerate thumbnails for all files'),
});

export const regenerateThumbnailResponseDefault = null;

export const regenerateThumbnailResponse = zod.unknown().nullable();

export const getImageAssetRepresentationParams = zod.object({
  fileId: zod.string().describe('FileId'),
  reprId: zod.string().describe('ImageRepresentationId'),
});

export const getFileDetailsParams = zod.object({
  id: zod.string().describe('FileId'),
});

export const getFileDetailsResponse = zod.object({
  exiftoolOutput: zod.unknown(),
});

export const getOriginalFileParams = zod.object({
  id: zod.string().describe('FileId'),
});

export const getThumbnailParams = zod.object({
  id: zod.string().describe('FileId to get thumbnail for'),
  size: zod.enum(['small', 'large']).describe('Thumbnail size'),
  format: zod.enum(['avif', 'webp']).describe('Image format for thumbnail'),
});

export const setAssetTransformCorrectionParams = zod.object({
  id: zod.string().describe('FileId'),
});

export const setAssetTransformCorrectionBody = zod.object({
  mirror: zod.enum(['none', 'horizontal', 'vertical']).nullish(),
  rotation: zod.number().nullish().describe('One of 0, 90, 180, 270'),
});

export const setAssetTransformCorrectionResponse = zod.object({
  mirror: zod.enum(['none', 'horizontal', 'vertical']),
  rotation: zod.number().describe('One of 0, 90, 180, 270'),
});

export const createSeriesBody = zod.object({
  assetIds: zod.array(zod.string()),
});

export const createSeriesResponse = zod.object({
  seriesId: zod.string(),
});

export const deleteSeriesParams = zod.object({
  id: zod.string().describe('AssetSeriesId'),
});

export const deleteSeriesResponseDefault = null;

export const deleteSeriesResponse = zod.unknown().nullable();

export const addAssetsToSeriesParams = zod.object({
  id: zod.string().describe('AssetSeriesId'),
});

export const addAssetsToSeriesBody = zod.object({
  assetIds: zod.array(zod.string()),
});

export const addAssetsToSeriesResponseSelectionIndicesItemMin = 0;

export const addAssetsToSeriesResponse = zod.object({
  assetIds: zod.array(zod.string()),
  id: zod.string(),
  selectionIndices: zod.array(zod.number().min(addAssetsToSeriesResponseSelectionIndicesItemMin)),
});

export const getTimelineSectionsQueryParams = zod.object({
  initialAssetId: zod.string().nullish(),
});

export const getTimelineSectionsResponseInitialAssetSectionSegmentsItemItemsItemSelectionIndicesItemMin = 0;

export const getTimelineSectionsResponse = zod.object({
  initialAssetSection: zod
    .object({
      sectionId: zod.string(),
      segments: zod.array(
        zod
          .union([
            zod.object({
              end: zod.string().datetime({}),
              start: zod.string().datetime({}),
              type: zod.enum(['dateRange']),
            }),
            zod.object({
              id: zod.string(),
              name: zod.string().nullish(),
              type: zod.enum(['userGroup']),
            }),
          ])
          .and(
            zod.object({
              items: zod.array(
                zod.union([
                  zod
                    .object({
                      assetId: zod.string(),
                      repFile: zod.object({
                        addedAt: zod.string().datetime({}),
                        assetRootId: zod.string(),
                        fileId: zod.string(),
                        height: zod.number(),
                        mimeType: zod.string(),
                        mirrorCorrection: zod.enum(['none', 'horizontal', 'vertical']),
                        pathInRoot: zod.string(),
                        rotationCorrection: zod.number(),
                        thumbhash: zod.string().nullish(),
                        width: zod.number(),
                      }),
                      takenDate: zod.string().datetime({}),
                    })
                    .and(
                      zod.union([
                        zod
                          .object({
                            representations: zod.array(
                              zod.object({
                                format: zod.string(),
                                height: zod.number(),
                                id: zod.string(),
                                size: zod.number(),
                                width: zod.number(),
                              }),
                            ),
                          })
                          .and(
                            zod.object({
                              assetType: zod.enum(['image']),
                            }),
                          ),
                        zod
                          .object({
                            hasDash: zod.boolean(),
                          })
                          .and(
                            zod.object({
                              assetType: zod.enum(['video']),
                            }),
                          ),
                      ]),
                    )
                    .and(zod.object({}))
                    .and(
                      zod.object({
                        itemType: zod.enum(['asset']),
                      }),
                    ),
                  zod.object({
                    assets: zod
                      .array(
                        zod
                          .object({
                            assetId: zod.string(),
                            repFile: zod.object({
                              addedAt: zod.string().datetime({}),
                              assetRootId: zod.string(),
                              fileId: zod.string(),
                              height: zod.number(),
                              mimeType: zod.string(),
                              mirrorCorrection: zod.enum(['none', 'horizontal', 'vertical']),
                              pathInRoot: zod.string(),
                              rotationCorrection: zod.number(),
                              thumbhash: zod.string().nullish(),
                              width: zod.number(),
                            }),
                            takenDate: zod.string().datetime({}),
                          })
                          .and(
                            zod.union([
                              zod
                                .object({
                                  representations: zod.array(
                                    zod.object({
                                      format: zod.string(),
                                      height: zod.number(),
                                      id: zod.string(),
                                      size: zod.number(),
                                      width: zod.number(),
                                    }),
                                  ),
                                })
                                .and(
                                  zod.object({
                                    assetType: zod.enum(['image']),
                                  }),
                                ),
                              zod
                                .object({
                                  hasDash: zod.boolean(),
                                })
                                .and(
                                  zod.object({
                                    assetType: zod.enum(['video']),
                                  }),
                                ),
                            ]),
                          )
                          .and(zod.object({})),
                      )
                      .describe('assets[0] is most recent, last is oldest asset'),
                    itemType: zod.enum(['assetSeries']),
                    selectionIndices: zod.array(
                      zod
                        .number()
                        .min(
                          getTimelineSectionsResponseInitialAssetSectionSegmentsItemItemsItemSelectionIndicesItemMin,
                        ),
                    ),
                    seriesId: zod.string(),
                  }),
                ]),
              ),
              sortDate: zod.string().datetime({}),
            }),
          ),
      ),
    })
    .nullish(),
  monthsSummary: zod.array(
    zod.array(
      zod.object({
        month: zod.number(),
        numAssets: zod.number(),
        totalNormalizedWidth: zod.number(),
        year: zod.number(),
      }),
    ),
  ),
  sections: zod.array(
    zod.object({
      endDate: zod.string().datetime({}).describe('date of \*oldest\* asset in range'),
      id: zod.string(),
      numAssets: zod.number(),
      startDate: zod.string().datetime({}).describe('date of \*most recent\* asset in range'),
      totalNormalizedWidth: zod.number(),
    }),
  ),
});

export const getTimelineSegmentsParams = zod.object({
  id: zod.string().describe('Section id'),
});

export const getTimelineSegmentsResponseSegmentsItemItemsItemSelectionIndicesItemMin = 0;

export const getTimelineSegmentsResponse = zod.object({
  segments: zod.array(
    zod
      .union([
        zod.object({
          end: zod.string().datetime({}),
          start: zod.string().datetime({}),
          type: zod.enum(['dateRange']),
        }),
        zod.object({
          id: zod.string(),
          name: zod.string().nullish(),
          type: zod.enum(['userGroup']),
        }),
      ])
      .and(
        zod.object({
          items: zod.array(
            zod.union([
              zod
                .object({
                  assetId: zod.string(),
                  repFile: zod.object({
                    addedAt: zod.string().datetime({}),
                    assetRootId: zod.string(),
                    fileId: zod.string(),
                    height: zod.number(),
                    mimeType: zod.string(),
                    mirrorCorrection: zod.enum(['none', 'horizontal', 'vertical']),
                    pathInRoot: zod.string(),
                    rotationCorrection: zod.number(),
                    thumbhash: zod.string().nullish(),
                    width: zod.number(),
                  }),
                  takenDate: zod.string().datetime({}),
                })
                .and(
                  zod.union([
                    zod
                      .object({
                        representations: zod.array(
                          zod.object({
                            format: zod.string(),
                            height: zod.number(),
                            id: zod.string(),
                            size: zod.number(),
                            width: zod.number(),
                          }),
                        ),
                      })
                      .and(
                        zod.object({
                          assetType: zod.enum(['image']),
                        }),
                      ),
                    zod
                      .object({
                        hasDash: zod.boolean(),
                      })
                      .and(
                        zod.object({
                          assetType: zod.enum(['video']),
                        }),
                      ),
                  ]),
                )
                .and(zod.object({}))
                .and(
                  zod.object({
                    itemType: zod.enum(['asset']),
                  }),
                ),
              zod.object({
                assets: zod
                  .array(
                    zod
                      .object({
                        assetId: zod.string(),
                        repFile: zod.object({
                          addedAt: zod.string().datetime({}),
                          assetRootId: zod.string(),
                          fileId: zod.string(),
                          height: zod.number(),
                          mimeType: zod.string(),
                          mirrorCorrection: zod.enum(['none', 'horizontal', 'vertical']),
                          pathInRoot: zod.string(),
                          rotationCorrection: zod.number(),
                          thumbhash: zod.string().nullish(),
                          width: zod.number(),
                        }),
                        takenDate: zod.string().datetime({}),
                      })
                      .and(
                        zod.union([
                          zod
                            .object({
                              representations: zod.array(
                                zod.object({
                                  format: zod.string(),
                                  height: zod.number(),
                                  id: zod.string(),
                                  size: zod.number(),
                                  width: zod.number(),
                                }),
                              ),
                            })
                            .and(
                              zod.object({
                                assetType: zod.enum(['image']),
                              }),
                            ),
                          zod
                            .object({
                              hasDash: zod.boolean(),
                            })
                            .and(
                              zod.object({
                                assetType: zod.enum(['video']),
                              }),
                            ),
                        ]),
                      )
                      .and(zod.object({})),
                  )
                  .describe('assets[0] is most recent, last is oldest asset'),
                itemType: zod.enum(['assetSeries']),
                selectionIndices: zod.array(
                  zod
                    .number()
                    .min(getTimelineSegmentsResponseSegmentsItemItemsItemSelectionIndicesItemMin),
                ),
                seriesId: zod.string(),
              }),
            ]),
          ),
          sortDate: zod.string().datetime({}),
        }),
      ),
  ),
});

export const createTimelineGroupBody = zod.object({
  assets: zod.array(zod.string()),
  name: zod.string(),
});

export const createTimelineGroupResponse = zod.object({
  displayDate: zod.string().datetime({}),
  timelineGroupId: zod.string(),
});

export const editTimelineGroupParams = zod.object({
  id: zod.string().describe('timeline group id'),
});

export const editTimelineGroupBody = zod.object({
  assets: zod.array(zod.string()),
  operation: zod.enum(['add', 'remove']),
});
