/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * myrti
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';

export interface AddAssetsToSeriesRequest {
  assetIds: AssetId[];
}

export interface Album {
  changedAt: string;
  createdAt: string;
  /** @nullable */
  description?: string | null;
  id: AlbumId;
  /** @nullable */
  name?: string | null;
  numAssets: number;
}

export interface AlbumDetailsResponse {
  /** @nullable */
  description?: string | null;
  items: AlbumItem[];
  /** @nullable */
  name?: string | null;
}

export type AlbumId = string;

export type AlbumItemAllOf = {
  itemId: AlbumItemId;
};

export type AlbumItem = AlbumItemType & AlbumItemAllOf;

export type AlbumItemId = string;

export type AlbumItemTypeOneOfItemType =
  (typeof AlbumItemTypeOneOfItemType)[keyof typeof AlbumItemTypeOneOfItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumItemTypeOneOfItemType = {
  asset: 'asset',
} as const;

export type AlbumItemTypeOneOf = {
  asset: AssetWithSpe;
  itemType: AlbumItemTypeOneOfItemType;
};

export type AlbumItemTypeOneOfThreeItemType =
  (typeof AlbumItemTypeOneOfThreeItemType)[keyof typeof AlbumItemTypeOneOfThreeItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AlbumItemTypeOneOfThreeItemType = {
  text: 'text',
} as const;

export type AlbumItemTypeOneOfThree = {
  itemType: AlbumItemTypeOneOfThreeItemType;
  text: string;
};

export type AlbumItemType = AlbumItemTypeOneOf | AlbumItemTypeOneOfThree;

export interface AppendAssetsRequest {
  assetIds: AssetId[];
}

export interface AppendAssetsResponse {
  success: boolean;
}

export interface Asset {
  assetId: AssetId;
  repFile: AssetFile;
  takenDate: string;
}

export interface AssetDetailsResponse {
  exiftoolOutput: unknown;
}

export interface AssetFile {
  addedAt: string;
  assetRootId: AssetRootDirId;
  fileId: FileId;
  height: number;
  mimeType: string;
  mirrorCorrection: MirrorCorrection;
  pathInRoot: string;
  rotationCorrection: number;
  /** @nullable */
  thumbhash?: string | null;
  width: number;
}

export type AssetId = string;

export type AssetRootDirId = string;

export interface AssetSeries {
  assetIds: AssetId[];
  id: AssetSeriesId;
  selectionIndices: number[];
}

export type AssetSeriesId = string;

export type AssetSpeOneOfAllOfAssetType =
  (typeof AssetSpeOneOfAllOfAssetType)[keyof typeof AssetSpeOneOfAllOfAssetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetSpeOneOfAllOfAssetType = {
  image: 'image',
} as const;

export type AssetSpeOneOfAllOf = {
  assetType: AssetSpeOneOfAllOfAssetType;
};

export type AssetSpeOneOf = Image & AssetSpeOneOfAllOf;

export type AssetSpeOneOfFourAllOfAssetType =
  (typeof AssetSpeOneOfFourAllOfAssetType)[keyof typeof AssetSpeOneOfFourAllOfAssetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetSpeOneOfFourAllOfAssetType = {
  video: 'video',
} as const;

export type AssetSpeOneOfFourAllOf = {
  assetType: AssetSpeOneOfFourAllOfAssetType;
};

export type AssetSpeOneOfFour = Video & AssetSpeOneOfFourAllOf;

export type AssetSpe = AssetSpeOneOf | AssetSpeOneOfFour;

export type AssetType = (typeof AssetType)[keyof typeof AssetType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetType = {
  image: 'image',
  video: 'video',
} as const;

export type AssetWithSpeAllOf = { [key: string]: unknown };

export type AssetWithSpe = Asset & AssetSpe & AssetWithSpeAllOf;

export interface CreateAlbumRequest {
  assets: AssetId[];
  /** @nullable */
  description?: string | null;
  name: string;
}

export interface CreateAlbumResponse {
  albumId: number;
}

export interface CreateSeriesRequest {
  assetIds: AssetId[];
}

export interface CreateSeriesResponse {
  seriesId: AssetSeriesId;
}

export interface CreateTimelineGroupRequest {
  assets: AssetId[];
  name: string;
}

export interface CreateTimelineGroupResponse {
  displayDate: string;
  timelineGroupId: TimelineGroupId;
}

export interface DeleteAlbumItemRequest {
  itemIds: AlbumItemId[];
}

export type EditTimelineGroup = (typeof EditTimelineGroup)[keyof typeof EditTimelineGroup];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EditTimelineGroup = {
  add: 'add',
  remove: 'remove',
} as const;

export interface EditTimelineGroupRequest {
  assets: AssetId[];
  groupId: TimelineGroupId;
  operation: EditTimelineGroup;
}

export type FileId = string;

export type HideAssetAction = (typeof HideAssetAction)[keyof typeof HideAssetAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HideAssetAction = {
  hide: 'hide',
  unhide: 'unhide',
} as const;

export interface HideAssetsRequest {
  assetIds: AssetId[];
  what: HideAssetAction;
}

export interface Image {
  representations: ImageRepresentation[];
}

export interface ImageRepresentation {
  format: string;
  height: number;
  id: string;
  size: number;
  width: number;
}

export type ImageRepresentationId = string;

export type MirrorCorrection = (typeof MirrorCorrection)[keyof typeof MirrorCorrection];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MirrorCorrection = {
  none: 'none',
  horizontal: 'horizontal',
  vertical: 'vertical',
} as const;

export type SegmentTypeOneOfType = (typeof SegmentTypeOneOfType)[keyof typeof SegmentTypeOneOfType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SegmentTypeOneOfType = {
  dateRange: 'dateRange',
} as const;

export type SegmentTypeOneOf = {
  end: string;
  start: string;
  type: SegmentTypeOneOfType;
};

export type SegmentTypeOneOfThreeType =
  (typeof SegmentTypeOneOfThreeType)[keyof typeof SegmentTypeOneOfThreeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SegmentTypeOneOfThreeType = {
  userGroup: 'userGroup',
} as const;

export type SegmentTypeOneOfThree = {
  id: TimelineGroupId;
  /** @nullable */
  name?: string | null;
  type: SegmentTypeOneOfThreeType;
};

export type SegmentType = SegmentTypeOneOf | SegmentTypeOneOfThree;

export interface SetAssetIsSeriesSelectionResponse {
  assetIds: AssetId[];
  selectionIndices: number[];
  seriesId: AssetSeriesId;
}

/**
 * @nullable
 */
export type SetAssetRotationRequestMirror = MirrorCorrection | null;

export interface SetAssetRotationRequest {
  /** @nullable */
  mirror?: SetAssetRotationRequestMirror;
  /**
   * One of 0, 90, 180, 270
   * @nullable
   */
  rotation?: number | null;
}

export interface SetAssetSeriesSelectionRequest {
  isSeriesSelection: boolean;
}

export type ThumbnailFormat = (typeof ThumbnailFormat)[keyof typeof ThumbnailFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThumbnailFormat = {
  avif: 'avif',
  webp: 'webp',
} as const;

export type ThumbnailSize = (typeof ThumbnailSize)[keyof typeof ThumbnailSize];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThumbnailSize = {
  small: 'small',
  large: 'large',
} as const;

export type TimelineGroupId = string;

export type TimelineItemOneOfAllOfItemType =
  (typeof TimelineItemOneOfAllOfItemType)[keyof typeof TimelineItemOneOfAllOfItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimelineItemOneOfAllOfItemType = {
  asset: 'asset',
} as const;

export type TimelineItemOneOfAllOf = {
  itemType: TimelineItemOneOfAllOfItemType;
};

export type TimelineItemOneOf = AssetWithSpe & TimelineItemOneOfAllOf;

export type TimelineItemOneOfFourItemType =
  (typeof TimelineItemOneOfFourItemType)[keyof typeof TimelineItemOneOfFourItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimelineItemOneOfFourItemType = {
  assetSeries: 'assetSeries',
} as const;

export type TimelineItemOneOfFour = {
  /** assets[0] is most recent, last is oldest asset */
  assets: AssetWithSpe[];
  itemType: TimelineItemOneOfFourItemType;
  selectionIndices: number[];
  seriesId: AssetSeriesId;
  /** @minimum 0 */
  totalSize: number;
};

export type TimelineItem = TimelineItemOneOf | TimelineItemOneOfFour;

export interface TimelineMonthSlice {
  month: number;
  numAssets: number;
  totalNormalizedWidth: number;
  year: number;
}

export interface TimelineSection {
  /** date of *oldest* asset in range */
  endDate: string;
  id: TimelineSectionId;
  numAssets: number;
  /** date of *most recent* asset in range */
  startDate: string;
  totalNormalizedWidth: number;
}

export type TimelineSectionId = string;

export interface TimelineSectionsResponse {
  monthsSummary: TimelineMonthSlice[][];
  sections: TimelineSection[];
}

export type TimelineSegmentAllOf = {
  items: TimelineItem[];
  sortDate: string;
};

export type TimelineSegment = SegmentType & TimelineSegmentAllOf;

export interface TimelineSegmentsResponse {
  segments: TimelineSegment[];
}

export interface Video {
  hasDash: boolean;
}

/**
 * @nullable
 */
export type DeleteAlbumItems200 = unknown | null;

/**
 * @nullable
 */
export type DeleteSeries200 = unknown | null;

export const getAllAlbums = <TData = AxiosResponse<Album[]>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/albums`, options);
};

export const createAlbum = <TData = AxiosResponse<CreateAlbumResponse>>(
  createAlbumRequest: CreateAlbumRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/albums`, createAlbumRequest, options);
};

export const getAlbumDetails = <TData = AxiosResponse<AlbumDetailsResponse>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/albums/${id}`, options);
};

export const appendAssetsToAlbum = <TData = AxiosResponse<AppendAssetsResponse>>(
  id: string,
  appendAssetsRequest: AppendAssetsRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.put(`/api/albums/${id}/assets`, appendAssetsRequest, options);
};

export const deleteAlbumItems = <TData = AxiosResponse<DeleteAlbumItems200>>(
  id: string,
  deleteAlbumItemRequest: DeleteAlbumItemRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/albums/${id}/deleteItems`, deleteAlbumItemRequest, options);
};

export const getAlbumThumbnail = <TData = AxiosResponse<string>>(
  id: AlbumId,
  size: string,
  format: ThumbnailFormat,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/albums/${id}/thumbnail/${size}/${format}`, {
    ...options,
  });
};

export const setAssetsHidden = <TData = AxiosResponse<void>>(
  hideAssetsRequest: HideAssetsRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/assets/hidden`, hideAssetsRequest, options);
};

export const getAsset = <TData = AxiosResponse<Asset>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/assets/${id}`, options);
};

export const setAssetIsSeriesSelection = <TData = AxiosResponse<SetAssetIsSeriesSelectionResponse>>(
  id: string,
  setAssetSeriesSelectionRequest: SetAssetSeriesSelectionRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/assets/${id}/seriesSelection`, setAssetSeriesSelectionRequest, options);
};

export const getOriginalFile = <TData = AxiosResponse<string>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/files/original/${id}`, {
    ...options,
  });
};

export const getImageAssetRepresentation = <TData = AxiosResponse<string>>(
  fileId: FileId,
  reprId: ImageRepresentationId,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/files/repr/${fileId}/${reprId}`, {
    ...options,
  });
};

export const getThumbnail = <TData = AxiosResponse<string>>(
  id: FileId,
  size: ThumbnailSize,
  format: ThumbnailFormat,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/files/thumbnail/${id}/${size}/${format}`, {
    ...options,
  });
};

export const getFileDetails = <TData = AxiosResponse<AssetDetailsResponse>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/files/${id}/details`, options);
};

export const setAssetTransformCorrection = <TData = AxiosResponse<AssetWithSpe>>(
  id: string,
  setAssetRotationRequest: SetAssetRotationRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/files/${id}/transform`, setAssetRotationRequest, options);
};

export const getAllAssetsGeojson = <TData = AxiosResponse<string>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/map/assetPoints`, {
    responseType: 'text',
    ...options,
  });
};

export const createSeries = <TData = AxiosResponse<CreateSeriesResponse>>(
  createSeriesRequest: CreateSeriesRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/photoSeries`, createSeriesRequest, options);
};

export const deleteSeries = <TData = AxiosResponse<DeleteSeries200>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/api/photoSeries/:id`, options);
};

export const addAssetsToSeries = <TData = AxiosResponse<AssetSeries>>(
  addAssetsToSeriesRequest: AddAssetsToSeriesRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(`/api/photoSeries/:id`, addAssetsToSeriesRequest, options);
};

export const rebuildTimeline = <TData = AxiosResponse<void>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/timeline/rebuild`, undefined, options);
};

export const getTimelineSections = <TData = AxiosResponse<TimelineSectionsResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/timeline/sections`, options);
};

export const getTimelineSegments = <TData = AxiosResponse<TimelineSegmentsResponse>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/api/timeline/sections/${id}`, options);
};

export const createTimelineGroup = <TData = AxiosResponse<CreateTimelineGroupResponse>>(
  createTimelineGroupRequest: CreateTimelineGroupRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/api/timelinegroups`, createTimelineGroupRequest, options);
};

export const editTimelineGroup = <TData = AxiosResponse<void>>(
  editTimelineGroupRequest: EditTimelineGroupRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.patch(`/api/timelinegroups`, editTimelineGroupRequest, options);
};

export type GetAllAlbumsResult = AxiosResponse<Album[]>;
export type CreateAlbumResult = AxiosResponse<CreateAlbumResponse>;
export type GetAlbumDetailsResult = AxiosResponse<AlbumDetailsResponse>;
export type AppendAssetsToAlbumResult = AxiosResponse<AppendAssetsResponse>;
export type DeleteAlbumItemsResult = AxiosResponse<DeleteAlbumItems200>;
export type GetAlbumThumbnailResult = AxiosResponse<string>;
export type SetAssetsHiddenResult = AxiosResponse<void>;
export type GetAssetResult = AxiosResponse<Asset>;
export type SetAssetIsSeriesSelectionResult = AxiosResponse<SetAssetIsSeriesSelectionResponse>;
export type GetOriginalFileResult = AxiosResponse<string>;
export type GetImageAssetRepresentationResult = AxiosResponse<string>;
export type GetThumbnailResult = AxiosResponse<string>;
export type GetFileDetailsResult = AxiosResponse<AssetDetailsResponse>;
export type SetAssetTransformCorrectionResult = AxiosResponse<AssetWithSpe>;
export type GetAllAssetsGeojsonResult = AxiosResponse<string>;
export type CreateSeriesResult = AxiosResponse<CreateSeriesResponse>;
export type DeleteSeriesResult = AxiosResponse<DeleteSeries200>;
export type AddAssetsToSeriesResult = AxiosResponse<AssetSeries>;
export type RebuildTimelineResult = AxiosResponse<void>;
export type GetTimelineSectionsResult = AxiosResponse<TimelineSectionsResponse>;
export type GetTimelineSegmentsResult = AxiosResponse<TimelineSegmentsResponse>;
export type CreateTimelineGroupResult = AxiosResponse<CreateTimelineGroupResponse>;
export type EditTimelineGroupResult = AxiosResponse<void>;
