[package]
name = "myrti-core"
version = "0.1.0"
edition = "2024"

[features]
__private-test = []

[dependencies]
myrti-data = { path = "../myrti-data" }

camino = { workspace = true }
chrono = { workspace = true }
claims = "0.7.1"
enum_dispatch = "0.3.12"
eyre = { workspace = true }
fasthash = "0.4.0"
futures = { workspace = true }
itertools = { workspace = true }
rayon = "1.7.0"
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.7.0"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
toml = "0.7.6"
tracing = { workspace = true }
walkdir = "2.3.3"
is_sorted = "0.1.1"
strum = { version = "0.26.3", features = ["derive"] }
nix = { version = "0.29.0", features = ["signal"] }

regex = { version = "1.13.0", default-features = false, features = ["std", "unicode-perl"] }
url = "2.5.8"
serde_with = "3.21.0"
quick-xml = { version = "0.41.0", features = ["serialize", "overlapped-lists"] }
num-traits = "0.2.19"
iso8601 = "0.6.3"
globset = "0.4.19"
fast-thumbhash = "0.2.0"

[build-dependencies]
cc = "1.0.79"
pkg-config = "0.3.27"
bindgen = "0.72.1"

[dev-dependencies]
pretty_assertions = "1.4.0"
proptest = "1.3.1"

roxmltree = "0.21.1"
